# Generated by Django 5.2.10 on 2026-01-13 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', '排队中'), ('running', '运行中'), ('success', '成功'), ('failed', '失败')], default='queued', max_length=10, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度 (0-100)')),
                ('yolo_result_json', models.JSONField(blank=True, default=dict, verbose_name='YOLO 推理结果')),
                ('nlp_result_json', models.JSONField(blank=True, default=dict, verbose_name='NLP 解析结果')),
                ('inference_result_json', models.JSONField(blank=True, default=dict, verbose_name='辨证推理结果')),
                ('explanation_text', models.TextField(blank=True, default='', verbose_name='解释文本')),
                ('timing_json', models.JSONField(blank=True, default=dict, verbose_name='各阶段耗时')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_runs', to='cases.case', verbose_name='病例')),
            ],
            options={
                'verbose_name': '流水线运行',
                'verbose_name_plural': '流水线运行',
                'db_table': 'pipeline_run',
                'ordering': ['-created_at'],
            },
        ),
    ]
