# Generated by Django 5.2.10 on 2026-01-13 15:21

import apps.cases.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('running', '运行中'), ('pending_review', '待审核'), ('approved', '已通过'), ('rejected', '已驳回'), ('failed', '失败')], default='draft', max_length=20, verbose_name='状态')),
                ('chief_complaint_text', models.TextField(blank=True, default='', verbose_name='主诉')),
                ('questionnaire_json', models.JSONField(blank=True, default=dict, verbose_name='问诊问卷')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL, verbose_name='患者')),
            ],
            options={
                'verbose_name': '病例',
                'verbose_name_plural': '病例',
                'db_table': 'case',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('raw_image', '原始图像'), ('mask', '分割掩码'), ('heatmap', '热力图'), ('annotated', '标注图像')], max_length=20, verbose_name='资源类型')),
                ('file', models.FileField(upload_to=apps.cases.models.case_asset_upload_path, verbose_name='文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='cases.case', verbose_name='病例')),
            ],
            options={
                'verbose_name': '病例资源',
                'verbose_name_plural': '病例资源',
                'db_table': 'case_asset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', '通过'), ('rejected', '驳回')], max_length=10, verbose_name='审核决定')),
                ('edited_syndrome_json', models.JSONField(blank=True, default=dict, verbose_name='修改后的证候')),
                ('edited_prescription_json', models.JSONField(blank=True, default=dict, verbose_name='修改后的处方')),
                ('note', models.TextField(blank=True, default='', verbose_name='审核备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='审核时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cases.case', verbose_name='病例')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核医生')),
            ],
            options={
                'verbose_name': '审核记录',
                'verbose_name_plural': '审核记录',
                'db_table': 'review',
                'ordering': ['-created_at'],
            },
        ),
    ]
