# Generated by Django 5.2.10 on 2026-02-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_assigned_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='decision',
            field=models.CharField(choices=[('approved', '通过'), ('rejected', '驳回'), ('revise', '修订通过')], max_length=10, verbose_name='审核决定'),
        ),
    ]
