# Generated by Django 5.2.10 on 2026-02-28 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0003_alter_review_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medication_plan', to='cases.case', verbose_name='关联病例')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_plans', to=settings.AUTH_USER_MODEL, verbose_name='患者')),
            ],
            options={
                'verbose_name': '用药计划',
                'verbose_name_plural': '用药计划',
                'db_table': 'medication_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('slot', models.CharField(choices=[('morning', '晨间'), ('afternoon', '午后'), ('evening', '晚间')], max_length=10, verbose_name='时段')),
                ('taken', models.BooleanField(default=False, verbose_name='是否已服药')),
                ('feedback', models.TextField(blank=True, default='', verbose_name='主观反馈')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='followups.medicationplan', verbose_name='用药计划')),
            ],
            options={
                'verbose_name': '用药记录',
                'verbose_name_plural': '用药记录',
                'db_table': 'medication_log',
                'ordering': ['-date', 'slot'],
                'unique_together': {('plan', 'date', 'slot')},
            },
        ),
    ]
