# Generated by Django 5.2.10 on 2026-03-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationplan',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='计划结束日期'),
        ),
    ]
