# Generated by Django 5.2.10 on 2026-01-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], default='', max_length=10, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='user',
            name='hospital',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='所属医院'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='职称'),
        ),
        migrations.AddField(
            model_name='user',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='从业年限'),
        ),
    ]
