# Generated by Django 5.2.10 on 2026-01-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_age_user_gender_user_hospital_user_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('internal', '内科'), ('surgery', '外科'), ('gynecology', '妇科'), ('pediatrics', '儿科'), ('orthopedics', '骨伤科'), ('ent', '耳鼻喉科')], default='', max_length=20, verbose_name='科室'),
        ),
    ]
